### ISSUE TITLE
IDE internal error: Uncaught Error: Cannot read properties of undefined (reading '_past')

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1776]
**Describe the bug**
IDE internal error: Uncaught Error: Cannot read properties of undefined (reading '_past')

**To Reproduce**
Open attached VBFlexGridDemo.twinproj file.

Open on MainForm.frm.twin

Click on line 5 "Class MainForm"

Below error appears:
```
IDE internal error: Uncaught Error: Cannot read properties of undefined (reading '_past')

TypeError: Cannot read properties of undefined (reading '_past')
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/main.js:1:549679
    at Array.forEach (<anonymous>)
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/main.js:1:549219
    at n.invoke (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:145)
    at l.deliver (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2649)
    at o.fire (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2202)
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:712:16411
    at n.invoke (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:145)
    at c.deliver (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2649)
    at o.fire (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2202), 6, 119137, Error: Cannot read properties of undefined (reading '_past')

TypeError: Cannot read properties of undefined (reading '_past')
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/main.js:1:549679
    at Array.forEach (<anonymous>)
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/main.js:1:549219
    at n.invoke (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:145)
    at l.deliver (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2649)
    at o.fire (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2202)
    at http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:712:16411
    at n.invoke (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:145)
    at c.deliver (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C46FCB7%7D/monaco-editor-0.35.1-pre-min//vs/editor/editor.main.js:107:2649)
    at o.fire (http://localhost:51514/%7B5BE44DB0-75B2-43A1-A408-AE5A0C
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1111]

**Additional context**
[VBFlexGridDemo.twinproj.zip](https://github.com/twinbasic/twinbasic/files/14235652/VBFlexGridDemo.twinproj.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 449.  Thanks!
