### ISSUE TITLE
Files disappearing from Sources

### ISSUE THREAD

**Issue by KDGundermann** [twinbasic/twinbasic#365]
**Describe the bug**
Adding more files to a Projects, suddenly files are missing from the folder "Sources"

**To Reproduce**
Currently not able to reproduce. It happend to me twice. 
I started a new project from scratch and added files (basically copy/paste the code from my GitLab repository)

**Expected behavior**
Expect to not loosing files...

**Screenshots**
![twinBASIC_MissingFiles](https://user-images.githubusercontent.com/208315/129973337-dacda9a0-772a-4f11-ac9d-3ccb0ce50f0f.png)

in Open Editor Files there is ChronosDateTime_Factory.twin but it is missing in the sources folder 

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - twinBASIC compiler version v0.10.4563
 - VSCode 1.59.0 (system setup)

**Additional context**
twinbasic Language Server.log:
```
[Error - 22:37:49] Request textDocument/documentSymbol failed.
  Message: bad file
  Code: 123 
[Error - 22:37:49] Request textDocument/codeAction failed.
  Message: bad file
  Code: 123 
[Error - 22:37:49] Request textDocument/foldingRange failed.
  Message: bad file
  Code: 123 
[Error - 22:37:53] Request textDocument/codeAction failed.
  Message: bad file
  Code: 123 
[Error - 22:37:54] Request textDocument/codeAction failed.
  Message: bad file
  Code: 123 
[Error - 22:37:55] Request textDocument/foldingRange failed.
  Message: bad file
  Code: 123 
[Error - 22:37:55] Request textDocument/codeAction failed.
  Message: bad file
  Code: 123 
[Error - 22:37:55] Request textDocument/documentSymbol failed.
  Message: bad file
  Code: 123 
```
exthost.log
```
[2021-08-18 22:37:54.275] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:54.276] [exthost] [error] Error: bad file
	at handleResponse (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2021-08-18 22:37:55.141] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:55.141] [exthost] [error] Error: bad file
	at handleResponse (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2021-08-18 22:37:55.192] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:55.192] [exthost] [error] Error: bad file
	at handleResponse (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2021-08-18 22:37:55.239] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:55.239] [exthost] [error] Error: busy
	at c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\out\src\semanticTokens.js:100:27
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async x.provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:172388)
[2021-08-18 22:37:55.290] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:55.290] [exthost] [error] Error: bad file
	at handleResponse (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:461:21)
[2021-08-18 22:37:56.694] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:56.694] [exthost] [error] Error: busy
	at c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\out\src\semanticTokens.js:100:27
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async x.provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:172388)
[2021-08-18 22:37:56.724] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2021-08-18 22:37:56.725] [exthost] [error] Error: busy
	at c:\Users\K.Gundermann\.vscode\extensions\twinbasic.twinbasic-0.10.4563\out\src\semanticTokens.js:100:27
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by WaynePhillipsEA** [comment]
I suspect what happened here is that you probably had a file being edited in VS code at the time, and when you imported the other file(s), something in one of those files caused a hard crash in the compiler.  This then triggered the compiler to restart, which in turn causes the project to be reloaded from disk.  

The problem with this is that the twinproj file is only persisted to disk when there are no unsaved documents open in VS Code (i.e. it is saved to disk once the last edited document is saved), so you can potentially lose files that way since the stored version on disk is potentially out of date with the editor when the compiler restarts abruptly.

There is a fix for this coming as we will be working on #260 soon, and there is plan for changes to prevent this from happening in future.

**Comment by WaynePhillipsEA** [comment]
As this largely relates to the old VS Code plugin, it's time to close this.  #260 is still open and covers the needed changes to prevent such problems in the new IDE.
