### ISSUE TITLE
error log VS Code

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#694]
**Describe the bug**
Here an error log of Log (Extension Host)
Maybe it helps resolving something. Otherwise please close the issue and ignore.

The 'title' error seems to happen always and do not affect something. The other ones are not always.

**To Reproduce**
```
[2022-01-25 12:02:34.668] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2022-01-25 12:02:34.669] [exthost] [error] TypeError: Cannot read property 'document' of undefined
	at Object.getDocumentStorage (c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\out\src\documentMetaStorage.js:8:55)
	at Object.update (c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\out\src\paramHints.js:152:49)
	at Object.provideDocumentSemanticTokens (c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\out\src\semanticTokens.js:105:24)
	at B.provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:98728)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:120980
	at We._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:111974)
	at We.$provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:120958)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12097)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34341
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at n._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23523)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21057
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at w.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14900
	at Socket.T (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```
```
[2022-01-25 12:02:34.870] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2022-01-25 12:02:34.870] [exthost] [error] TypeError: Cannot read property 'title' of null
	at Object.is (c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\node_modules\vscode-languageserver-types\lib\umd\main.js:425:65)
	at c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\node_modules\vscode-languageclient\lib\common\client.js:1222:74
	at async T.provideCodeActions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:93216)
```

```
[2022-01-25 12:07:47.905] [exthost] [error] [twinbasic.twinbasic] provider FAILED
[2022-01-25 12:07:47.905] [exthost] [error] TypeError: Cannot read property 'customRequest' of undefined
	at Object.provideDocumentSemanticTokens (c:\Users\_username_\.vscode\extensions\twinbasic.twinbasic-0.13.91\out\src\semanticTokens.js:50:67)
	at B.provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:98728)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:120980
	at We._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:111974)
	at We.$provideDocumentSemanticTokens (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:120958)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13802)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:13486)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12097)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:10826)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:8922
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:34341
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:18942)
	at n._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:23523)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21057
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at w.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:14900
	at Socket.T (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:114:13813)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.91]

**Comment by Kr00l** [comment]
Here also some interesting "warnings" from the Log (Windows)
Maybe it has something todo with the "unable resolve workspace" issue I encounter very often (?)

```
[2022-01-25 15:43:32.896] [renderer1] [warning] Ignoring the error while validating workspace folder twinbasic-builds:/___BUILDS/ - No file system provider found for resource 'twinbasic-builds:/___BUILDS/'
[2022-01-25 15:43:33.154] [renderer1] [warning] Ignoring the error while validating workspace folder twinbasic:/NewProject/ - No file system provider found for resource 'twinbasic:/NewProject/'
```

**Comment by WaynePhillipsEA** [comment]
How often are you experiencing the 'unable resolve workspace' problem?

**Comment by Kr00l** [comment]
> How often are you experiencing the 'unable resolve workspace' problem?

Very often. Sometimes it opens, but display this yellow exclamation mark.
I just close workspace and open again. Sometimes it's failing 3x in a row.

**Comment by WaynePhillipsEA** [comment]
Oh wow, that's **_way_** more often than I expected.  Does this happen when opening any project, or a particular one?

**Comment by Kr00l** [comment]
> Oh wow, that's **_way_** more often than I expected. Does this happen when opening any project, or a particular one?

That doesn't seem to matter. It can be just the Standard Exe sample project.

**Comment by Kr00l** [comment]
> Thanks and sorry for all the questions. How do you usually open projects? Is it via Windows Explorer > opening the code-workspace file, or a different way?

Yes through the menu.

**Comment by WaynePhillipsEA** [comment]
OK, thanks.   Do you have any other VS Code extensions installed?  **When this problems occurs** could you:

1) go to the 'tB' activity panel on the left.  If the twinBASIC extension got activated, then it should list the Sample projects.  If the extension didn't get activated by VS Code, then that list will be empty.

2) take a screenshot and post here

Thanks!

**Comment by WaynePhillipsEA** [comment]
I just experienced this, but unfortunately didn't have the debugger attached.  A few notes when it happened:
- looks like I had shutdown VSCode with a form designer left open
- the twinBASIC extension definitely was not loaded at all by VS Code (the tB activity panel was empty, and no twinBASIC log)
- using the 'Developer: Reload Window' command in the command palette fixed it.  You could assign a keybinding to that command if this happens regularly.

**Comment by Kr00l** [comment]
Yes using 'Developer: Reload Window' helps. Thanks for the tip.

When it is planned that tB moves to Theia? prior to v1? If yes we may have to ignore it for the time being.

**Comment by WaynePhillipsEA** [comment]
Just as a FYI, this just happened to me whilst debugging the extension, so I managed to get a stack trace of the vscode point of error:

```
rejected promise not handled within 1 second: Error: Unknown actor MainThreadWindow  (extensionHostProcess.js:112)
stack trace: Error: Unknown actor MainThreadWindow
    at u._doInvokeHandler (workbench.desktop.main.js:1513:12904)
    at u._invokeHandler (workbench.desktop.main.js:1513:12784)
    at u._receiveRequest (workbench.desktop.main.js:1513:11446)
    at u._receiveOneMessage (workbench.desktop.main.js:1513:10124)
    at workbench.desktop.main.js:1513:8233
    at o.fire (workbench.desktop.main.js:67:1712)
    at l._deliverMessages (workbench.desktop.main.js:83:19451)
    at workbench.desktop.main.js:83:19196
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

After that, no extensions are properly loaded, and a reload of VS code is required to fix it.

**Comment by Kr00l** [comment]
I close this as VS Code is not relevant. If at some point VS code is re-supported fully things may change and if necessary a new issue may be created.
